package authservice.org.userservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "users")
public class User implements Serializable {

    private static final long serialVersionUID = 1L;
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "user_name")
    private String userName;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "password")
    private String password;

    @DynamoDBAttribute(attributeName = "information_user")
    private InformationUser informationUser;

    @DynamoDBAttribute(attributeName = "role_name")
    private Role roleName;

    @DynamoDBAttribute(attributeName = "is_active")
    @DynamoDBAutoGeneratedDefault(value = "false")
    private Boolean isActive;

    @DynamoDBAttribute(attributeName = "is_deleted")
    @DynamoDBAutoGeneratedDefault(value = "false")
    private Boolean isDeleted;

    @DynamoDBAttribute(attributeName = "is_locked")
    @DynamoDBAutoGeneratedDefault(value = "false")
    private Boolean isLocked;

    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_date")
    private Date createdDate;

    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "updated_date")
    private Date updatedDate;

}


