spring:
  application:
    name: discovery-server-eureka-service
server:
  port: 8761

eureka:
  instance:
    hostname: spring-cloud-gateway.discovery.svc
    homePageUrl: http://${eureka.instance.hostname}/
    statusPageUrl: http://${eureka.instance.hostname}/actuator/info/
    healthCheckUrl: http://${eureka.instance.hostname}/actuator/health/
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

