spring:
    application:
        name: users-service
    profiles:
        active: native

server:
    port: 9010

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka